// Authored translations, generated by build-locales.mjs
export const demoProducts={
  "sage-strategy": {
    "zh": {
      "title": "青岚 · 战略提案",
      "description": "用清晰层级和克制配色呈现想法。包含封面、方向、要点、可编辑图表与行动计划。",
      "metadata": {
        "editable": "文字、形状、原生图表",
        "fonts": "Arial 系统字体；不含字体文件",
        "images": "自有几何元素；无第三方图片",
        "license": "原创演示素材，文字、形状和图表可编辑。商业使用范围请先联系商家确认。"
      }
    },
    "zh-TW": {
      "title": "青嵐 · 策略提案",
      "description": "以清晰層級與精簡配色表達想法。含封面、方向、重點、可編輯圖表與行動計畫。",
      "metadata": {
        "editable": "文字、形狀、原生圖表",
        "fonts": "Arial 系統字型；不含字型檔",
        "images": "自有幾何元素；無第三方圖片",
        "license": "原創簡報素材，文字、形狀及圖表可編輯。商業使用範圍請先聯絡商家確認。"
      }
    },
    "en": {
      "title": "Sage Strategy",
      "description": "Present ideas with a considered palette and clear hierarchy. Includes a cover, direction, priorities, an editable chart and next steps.",
      "metadata": {
        "editable": "Text, shapes and native charts",
        "fonts": "Arial system font; font files not included",
        "images": "Original geometry; no third-party images",
        "license": "Original presentation assets with editable text, shapes and charts. Contact the seller to confirm commercial usage rights."
      }
    },
    "ja": {
      "title": "セージ・戦略提案",
      "description": "落ち着いた配色と明確な構成でアイデアを伝えます。表紙、方針、重点、編集可能なグラフ、行動計画を収録。",
      "metadata": {
        "editable": "テキスト、図形、ネイティブグラフ",
        "fonts": "Arial システムフォント、フォントファイルなし",
        "images": "独自の幾何図形、外部画像なし",
        "license": "文字・図形・グラフを編集できるオリジナル素材です。商用利用の範囲は販売者にご確認ください。"
      }
    },
    "ko": {
      "title": "세이지 전략 제안",
      "description": "차분한 색상과 명확한 구성으로 아이디어를 전달하세요. 표지, 방향, 우선순위, 편집 가능한 차트와 실행 계획이 포함됩니다.",
      "metadata": {
        "editable": "텍스트, 도형, 기본 차트",
        "fonts": "Arial 시스템 글꼴, 글꼴 파일 미포함",
        "images": "자체 제작 도형, 외부 이미지 없음",
        "license": "텍스트, 도형과 차트를 편집할 수 있는 원본 자료입니다. 상업 이용 범위는 판매자에게 확인하세요."
      }
    },
    "fr": {
      "title": "Stratégie Sauge",
      "description": "Présentez vos idées avec une palette sobre et une hiérarchie claire. Couverture, orientation, priorités, graphique modifiable et prochaines étapes inclus.",
      "metadata": {
        "editable": "Texte, formes et graphiques natifs",
        "fonts": "Police système Arial ; fichiers non inclus",
        "images": "Géométrie originale ; aucune image tierce",
        "license": "Contenus originaux avec textes, formes et graphiques modifiables. Confirmez les droits commerciaux auprès du vendeur."
      }
    },
    "de": {
      "title": "Salbei-Strategie",
      "description": "Präsentieren Sie Ideen mit ruhigen Farben und klarer Struktur. Enthält Titelblatt, Ausrichtung, Schwerpunkte, bearbeitbares Diagramm und nächste Schritte.",
      "metadata": {
        "editable": "Text, Formen und native Diagramme",
        "fonts": "Systemschrift Arial; Schriftdateien nicht enthalten",
        "images": "Eigene Geometrie; keine fremden Bilder",
        "license": "Originale Inhalte mit bearbeitbaren Texten, Formen und Diagrammen. Kommerzielle Nutzungsrechte beim Verkäufer bestätigen."
      }
    },
    "es": {
      "title": "Estrategia Salvia",
      "description": "Presenta ideas con una paleta sobria y una jerarquía clara. Incluye portada, dirección, prioridades, un gráfico editable y próximos pasos.",
      "metadata": {
        "editable": "Texto, formas y gráficos nativos",
        "fonts": "Fuente del sistema Arial; archivos no incluidos",
        "images": "Geometría original; sin imágenes de terceros",
        "license": "Material original con texto, formas y gráficos editables. Consulta los derechos comerciales con el vendedor."
      }
    },
    "pt": {
      "title": "Estratégia Sálvia",
      "description": "Apresente ideias com cores discretas e organização clara. Inclui capa, direção, prioridades, gráfico editável e próximos passos.",
      "metadata": {
        "editable": "Texto, formas e gráficos nativos",
        "fonts": "Fonte do sistema Arial; arquivos não incluídos",
        "images": "Geometria original; sem imagens de terceiros",
        "license": "Material original com textos, formas e gráficos editáveis. Confirme os direitos comerciais com o vendedor."
      }
    },
    "ru": {
      "title": "Стратегия «Шалфей»",
      "description": "Передавайте идеи с помощью сдержанных цветов и ясной структуры. Обложка, направление, приоритеты, редактируемая диаграмма и план действий.",
      "metadata": {
        "editable": "Текст, фигуры и встроенные диаграммы",
        "fonts": "Системный шрифт Arial; файлы шрифтов не входят",
        "images": "Авторские геометрические элементы; без сторонних изображений",
        "license": "Оригинальные материалы с редактируемым текстом, фигурами и диаграммами. Уточните коммерческие права у продавца."
      }
    },
    "ar": {
      "title": "استراتيجية المريمية",
      "description": "اعرض أفكارك بألوان هادئة وتنظيم واضح. يتضمن غلافًا واتجاهًا وأولويات ورسمًا بيانيًا قابلًا للتحرير وخطوات تالية.",
      "metadata": {
        "editable": "النصوص والأشكال والرسوم البيانية الأصلية",
        "fonts": "خط النظام Arial؛ ملفات الخط غير مضمنة",
        "images": "أشكال هندسية أصلية؛ دون صور خارجية",
        "license": "مواد أصلية بنصوص وأشكال ورسوم قابلة للتحرير. أكد حقوق الاستخدام التجاري مع البائع."
      }
    },
    "hi": {
      "title": "सेज रणनीति",
      "description": "संतुलित रंगों और स्पष्ट संरचना से विचार प्रस्तुत करें। कवर, दिशा, प्राथमिकताएँ, संपादन योग्य चार्ट और आगे की योजना शामिल हैं।",
      "metadata": {
        "editable": "पाठ, आकृतियाँ और मूल चार्ट",
        "fonts": "Arial सिस्टम फ़ॉन्ट; फ़ॉन्ट फ़ाइलें शामिल नहीं",
        "images": "मूल ज्यामितीय आकृतियाँ; बाहरी चित्र नहीं",
        "license": "मौलिक सामग्री में पाठ, आकार और चार्ट संपादन योग्य हैं। व्यावसायिक उपयोग के अधिकार विक्रेता से पुष्टि करें।"
      }
    },
    "it": {
      "title": "Strategia Salvia",
      "description": "Presenta le idee con colori sobri e una struttura chiara. Include copertina, direzione, priorità, grafico modificabile e prossimi passi.",
      "metadata": {
        "editable": "Testo, forme e grafici nativi",
        "fonts": "Font di sistema Arial; file del font esclusi",
        "images": "Geometria originale; nessuna immagine di terzi",
        "license": "Materiali originali con testi, forme e grafici modificabili. Conferma i diritti commerciali con il venditore."
      }
    }
  },
  "coral-story": {
    "zh": {
      "title": "珊瑚 · 品牌叙事",
      "description": "用清晰层级和克制配色呈现想法。包含封面、方向、要点、可编辑图表与行动计划。",
      "metadata": {
        "editable": "文字、形状、原生图表",
        "fonts": "Arial 系统字体；不含字体文件",
        "images": "自有几何元素；无第三方图片",
        "license": "原创演示素材，文字、形状和图表可编辑。商业使用范围请先联系商家确认。"
      }
    },
    "zh-TW": {
      "title": "珊瑚 · 品牌故事",
      "description": "以清晰層級與精簡配色表達想法。含封面、方向、重點、可編輯圖表與行動計畫。",
      "metadata": {
        "editable": "文字、形狀、原生圖表",
        "fonts": "Arial 系統字型；不含字型檔",
        "images": "自有幾何元素；無第三方圖片",
        "license": "原創簡報素材，文字、形狀及圖表可編輯。商業使用範圍請先聯絡商家確認。"
      }
    },
    "en": {
      "title": "Coral Brand Story",
      "description": "Present ideas with a considered palette and clear hierarchy. Includes a cover, direction, priorities, an editable chart and next steps.",
      "metadata": {
        "editable": "Text, shapes and native charts",
        "fonts": "Arial system font; font files not included",
        "images": "Original geometry; no third-party images",
        "license": "Original presentation assets with editable text, shapes and charts. Contact the seller to confirm commercial usage rights."
      }
    },
    "ja": {
      "title": "コーラル・ブランドストーリー",
      "description": "落ち着いた配色と明確な構成でアイデアを伝えます。表紙、方針、重点、編集可能なグラフ、行動計画を収録。",
      "metadata": {
        "editable": "テキスト、図形、ネイティブグラフ",
        "fonts": "Arial システムフォント、フォントファイルなし",
        "images": "独自の幾何図形、外部画像なし",
        "license": "文字・図形・グラフを編集できるオリジナル素材です。商用利用の範囲は販売者にご確認ください。"
      }
    },
    "ko": {
      "title": "코랄 브랜드 이야기",
      "description": "차분한 색상과 명확한 구성으로 아이디어를 전달하세요. 표지, 방향, 우선순위, 편집 가능한 차트와 실행 계획이 포함됩니다.",
      "metadata": {
        "editable": "텍스트, 도형, 기본 차트",
        "fonts": "Arial 시스템 글꼴, 글꼴 파일 미포함",
        "images": "자체 제작 도형, 외부 이미지 없음",
        "license": "텍스트, 도형과 차트를 편집할 수 있는 원본 자료입니다. 상업 이용 범위는 판매자에게 확인하세요."
      }
    },
    "fr": {
      "title": "Histoire de marque Corail",
      "description": "Présentez vos idées avec une palette sobre et une hiérarchie claire. Couverture, orientation, priorités, graphique modifiable et prochaines étapes inclus.",
      "metadata": {
        "editable": "Texte, formes et graphiques natifs",
        "fonts": "Police système Arial ; fichiers non inclus",
        "images": "Géométrie originale ; aucune image tierce",
        "license": "Contenus originaux avec textes, formes et graphiques modifiables. Confirmez les droits commerciaux auprès du vendeur."
      }
    },
    "de": {
      "title": "Korallen-Markengeschichte",
      "description": "Präsentieren Sie Ideen mit ruhigen Farben und klarer Struktur. Enthält Titelblatt, Ausrichtung, Schwerpunkte, bearbeitbares Diagramm und nächste Schritte.",
      "metadata": {
        "editable": "Text, Formen und native Diagramme",
        "fonts": "Systemschrift Arial; Schriftdateien nicht enthalten",
        "images": "Eigene Geometrie; keine fremden Bilder",
        "license": "Originale Inhalte mit bearbeitbaren Texten, Formen und Diagrammen. Kommerzielle Nutzungsrechte beim Verkäufer bestätigen."
      }
    },
    "es": {
      "title": "Historia de marca Coral",
      "description": "Presenta ideas con una paleta sobria y una jerarquía clara. Incluye portada, dirección, prioridades, un gráfico editable y próximos pasos.",
      "metadata": {
        "editable": "Texto, formas y gráficos nativos",
        "fonts": "Fuente del sistema Arial; archivos no incluidos",
        "images": "Geometría original; sin imágenes de terceros",
        "license": "Material original con texto, formas y gráficos editables. Consulta los derechos comerciales con el vendedor."
      }
    },
    "pt": {
      "title": "História da marca Coral",
      "description": "Apresente ideias com cores discretas e organização clara. Inclui capa, direção, prioridades, gráfico editável e próximos passos.",
      "metadata": {
        "editable": "Texto, formas e gráficos nativos",
        "fonts": "Fonte do sistema Arial; arquivos não incluídos",
        "images": "Geometria original; sem imagens de terceiros",
        "license": "Material original com textos, formas e gráficos editáveis. Confirme os direitos comerciais com o vendedor."
      }
    },
    "ru": {
      "title": "История бренда «Коралл»",
      "description": "Передавайте идеи с помощью сдержанных цветов и ясной структуры. Обложка, направление, приоритеты, редактируемая диаграмма и план действий.",
      "metadata": {
        "editable": "Текст, фигуры и встроенные диаграммы",
        "fonts": "Системный шрифт Arial; файлы шрифтов не входят",
        "images": "Авторские геометрические элементы; без сторонних изображений",
        "license": "Оригинальные материалы с редактируемым текстом, фигурами и диаграммами. Уточните коммерческие права у продавца."
      }
    },
    "ar": {
      "title": "قصة علامة المرجان",
      "description": "اعرض أفكارك بألوان هادئة وتنظيم واضح. يتضمن غلافًا واتجاهًا وأولويات ورسمًا بيانيًا قابلًا للتحرير وخطوات تالية.",
      "metadata": {
        "editable": "النصوص والأشكال والرسوم البيانية الأصلية",
        "fonts": "خط النظام Arial؛ ملفات الخط غير مضمنة",
        "images": "أشكال هندسية أصلية؛ دون صور خارجية",
        "license": "مواد أصلية بنصوص وأشكال ورسوم قابلة للتحرير. أكد حقوق الاستخدام التجاري مع البائع."
      }
    },
    "hi": {
      "title": "कोरल ब्रांड की कहानी",
      "description": "संतुलित रंगों और स्पष्ट संरचना से विचार प्रस्तुत करें। कवर, दिशा, प्राथमिकताएँ, संपादन योग्य चार्ट और आगे की योजना शामिल हैं।",
      "metadata": {
        "editable": "पाठ, आकृतियाँ और मूल चार्ट",
        "fonts": "Arial सिस्टम फ़ॉन्ट; फ़ॉन्ट फ़ाइलें शामिल नहीं",
        "images": "मूल ज्यामितीय आकृतियाँ; बाहरी चित्र नहीं",
        "license": "मौलिक सामग्री में पाठ, आकार और चार्ट संपादन योग्य हैं। व्यावसायिक उपयोग के अधिकार विक्रेता से पुष्टि करें।"
      }
    },
    "it": {
      "title": "Storia del marchio Corallo",
      "description": "Presenta le idee con colori sobri e una struttura chiara. Include copertina, direzione, priorità, grafico modificabile e prossimi passi.",
      "metadata": {
        "editable": "Testo, forme e grafici nativi",
        "fonts": "Font di sistema Arial; file del font esclusi",
        "images": "Geometria originale; nessuna immagine di terzi",
        "license": "Materiali originali con testi, forme e grafici modificabili. Conferma i diritti commerciali con il venditore."
      }
    }
  },
  "midnight-report": {
    "zh": {
      "title": "深蓝 · 数据报告",
      "description": "用清晰层级和克制配色呈现想法。包含封面、方向、要点、可编辑图表与行动计划。",
      "metadata": {
        "editable": "文字、形状、原生图表",
        "fonts": "Arial 系统字体；不含字体文件",
        "images": "自有几何元素；无第三方图片",
        "license": "原创演示素材，文字、形状和图表可编辑。商业使用范围请先联系商家确认。"
      }
    },
    "zh-TW": {
      "title": "深藍 · 數據報告",
      "description": "以清晰層級與精簡配色表達想法。含封面、方向、重點、可編輯圖表與行動計畫。",
      "metadata": {
        "editable": "文字、形狀、原生圖表",
        "fonts": "Arial 系統字型；不含字型檔",
        "images": "自有幾何元素；無第三方圖片",
        "license": "原創簡報素材，文字、形狀及圖表可編輯。商業使用範圍請先聯絡商家確認。"
      }
    },
    "en": {
      "title": "Midnight Report",
      "description": "Present ideas with a considered palette and clear hierarchy. Includes a cover, direction, priorities, an editable chart and next steps.",
      "metadata": {
        "editable": "Text, shapes and native charts",
        "fonts": "Arial system font; font files not included",
        "images": "Original geometry; no third-party images",
        "license": "Original presentation assets with editable text, shapes and charts. Contact the seller to confirm commercial usage rights."
      }
    },
    "ja": {
      "title": "ミッドナイト・データレポート",
      "description": "落ち着いた配色と明確な構成でアイデアを伝えます。表紙、方針、重点、編集可能なグラフ、行動計画を収録。",
      "metadata": {
        "editable": "テキスト、図形、ネイティブグラフ",
        "fonts": "Arial システムフォント、フォントファイルなし",
        "images": "独自の幾何図形、外部画像なし",
        "license": "文字・図形・グラフを編集できるオリジナル素材です。商用利用の範囲は販売者にご確認ください。"
      }
    },
    "ko": {
      "title": "미드나잇 데이터 보고서",
      "description": "차분한 색상과 명확한 구성으로 아이디어를 전달하세요. 표지, 방향, 우선순위, 편집 가능한 차트와 실행 계획이 포함됩니다.",
      "metadata": {
        "editable": "텍스트, 도형, 기본 차트",
        "fonts": "Arial 시스템 글꼴, 글꼴 파일 미포함",
        "images": "자체 제작 도형, 외부 이미지 없음",
        "license": "텍스트, 도형과 차트를 편집할 수 있는 원본 자료입니다. 상업 이용 범위는 판매자에게 확인하세요."
      }
    },
    "fr": {
      "title": "Rapport Minuit",
      "description": "Présentez vos idées avec une palette sobre et une hiérarchie claire. Couverture, orientation, priorités, graphique modifiable et prochaines étapes inclus.",
      "metadata": {
        "editable": "Texte, formes et graphiques natifs",
        "fonts": "Police système Arial ; fichiers non inclus",
        "images": "Géométrie originale ; aucune image tierce",
        "license": "Contenus originaux avec textes, formes et graphiques modifiables. Confirmez les droits commerciaux auprès du vendeur."
      }
    },
    "de": {
      "title": "Mitternachtsbericht",
      "description": "Präsentieren Sie Ideen mit ruhigen Farben und klarer Struktur. Enthält Titelblatt, Ausrichtung, Schwerpunkte, bearbeitbares Diagramm und nächste Schritte.",
      "metadata": {
        "editable": "Text, Formen und native Diagramme",
        "fonts": "Systemschrift Arial; Schriftdateien nicht enthalten",
        "images": "Eigene Geometrie; keine fremden Bilder",
        "license": "Originale Inhalte mit bearbeitbaren Texten, Formen und Diagrammen. Kommerzielle Nutzungsrechte beim Verkäufer bestätigen."
      }
    },
    "es": {
      "title": "Informe Medianoche",
      "description": "Presenta ideas con una paleta sobria y una jerarquía clara. Incluye portada, dirección, prioridades, un gráfico editable y próximos pasos.",
      "metadata": {
        "editable": "Texto, formas y gráficos nativos",
        "fonts": "Fuente del sistema Arial; archivos no incluidos",
        "images": "Geometría original; sin imágenes de terceros",
        "license": "Material original con texto, formas y gráficos editables. Consulta los derechos comerciales con el vendedor."
      }
    },
    "pt": {
      "title": "Relatório Meia-noite",
      "description": "Apresente ideias com cores discretas e organização clara. Inclui capa, direção, prioridades, gráfico editável e próximos passos.",
      "metadata": {
        "editable": "Texto, formas e gráficos nativos",
        "fonts": "Fonte do sistema Arial; arquivos não incluídos",
        "images": "Geometria original; sem imagens de terceiros",
        "license": "Material original com textos, formas e gráficos editáveis. Confirme os direitos comerciais com o vendedor."
      }
    },
    "ru": {
      "title": "Отчёт «Полночь»",
      "description": "Передавайте идеи с помощью сдержанных цветов и ясной структуры. Обложка, направление, приоритеты, редактируемая диаграмма и план действий.",
      "metadata": {
        "editable": "Текст, фигуры и встроенные диаграммы",
        "fonts": "Системный шрифт Arial; файлы шрифтов не входят",
        "images": "Авторские геометрические элементы; без сторонних изображений",
        "license": "Оригинальные материалы с редактируемым текстом, фигурами и диаграммами. Уточните коммерческие права у продавца."
      }
    },
    "ar": {
      "title": "تقرير منتصف الليل",
      "description": "اعرض أفكارك بألوان هادئة وتنظيم واضح. يتضمن غلافًا واتجاهًا وأولويات ورسمًا بيانيًا قابلًا للتحرير وخطوات تالية.",
      "metadata": {
        "editable": "النصوص والأشكال والرسوم البيانية الأصلية",
        "fonts": "خط النظام Arial؛ ملفات الخط غير مضمنة",
        "images": "أشكال هندسية أصلية؛ دون صور خارجية",
        "license": "مواد أصلية بنصوص وأشكال ورسوم قابلة للتحرير. أكد حقوق الاستخدام التجاري مع البائع."
      }
    },
    "hi": {
      "title": "मिडनाइट रिपोर्ट",
      "description": "संतुलित रंगों और स्पष्ट संरचना से विचार प्रस्तुत करें। कवर, दिशा, प्राथमिकताएँ, संपादन योग्य चार्ट और आगे की योजना शामिल हैं।",
      "metadata": {
        "editable": "पाठ, आकृतियाँ और मूल चार्ट",
        "fonts": "Arial सिस्टम फ़ॉन्ट; फ़ॉन्ट फ़ाइलें शामिल नहीं",
        "images": "मूल ज्यामितीय आकृतियाँ; बाहरी चित्र नहीं",
        "license": "मौलिक सामग्री में पाठ, आकार और चार्ट संपादन योग्य हैं। व्यावसायिक उपयोग के अधिकार विक्रेता से पुष्टि करें।"
      }
    },
    "it": {
      "title": "Rapporto Mezzanotte",
      "description": "Presenta le idee con colori sobri e una struttura chiara. Include copertina, direzione, priorità, grafico modificabile e prossimi passi.",
      "metadata": {
        "editable": "Testo, forme e grafici nativi",
        "fonts": "Font di sistema Arial; file del font esclusi",
        "images": "Geometria originale; nessuna immagine di terzi",
        "license": "Materiali originali con testi, forme e grafici modificabili. Conferma i diritti commerciali con il venditore."
      }
    }
  }
} as const;
export const demoCategories={
  "business": {
    "zh": "商业提案",
    "zh-TW": "商業提案",
    "en": "Business",
    "ja": "ビジネス提案",
    "ko": "비즈니스 제안",
    "fr": "Affaires",
    "de": "Geschäftliches",
    "es": "Negocios",
    "pt": "Negócios",
    "ru": "Бизнес",
    "ar": "الأعمال",
    "hi": "व्यवसाय",
    "it": "Affari"
  },
  "creative": {
    "zh": "品牌创意",
    "zh-TW": "品牌創意",
    "en": "Creative",
    "ja": "ブランド・クリエイティブ",
    "ko": "브랜드 디자인",
    "fr": "Création",
    "de": "Kreatives",
    "es": "Creatividad",
    "pt": "Criatividade",
    "ru": "Творчество",
    "ar": "الإبداع",
    "hi": "रचनात्मक",
    "it": "Creatività"
  },
  "report": {
    "zh": "数据报告",
    "zh-TW": "數據報告",
    "en": "Reports",
    "ja": "データレポート",
    "ko": "데이터 보고서",
    "fr": "Rapports",
    "de": "Berichte",
    "es": "Informes",
    "pt": "Relatórios",
    "ru": "Отчёты",
    "ar": "التقارير",
    "hi": "रिपोर्ट",
    "it": "Rapporti"
  }
} as const;
