import fs from 'node:fs/promises';
import {languages,rows,sentences} from './locale-source.mjs';
import {operationsRows} from './operations-locales.mjs';
import {contentRows} from './content-locales.mjs';
import {titles,categories,description,metadata} from './demo-locales.mjs';
const dictionaries=Object.fromEntries(languages.map(language=>[language,{}]));
for(const line of (rows+'\n'+sentences+'\n'+operationsRows+'\n'+contentRows).split('\n')){const [key,...values]=line.split('|');if(values.length!==languages.length)throw new Error('Incomplete translation: '+key);for(let i=0;i<languages.length;i++){if(!values[i]||dictionaries[languages[i]][key])throw new Error('Invalid/duplicate translation: '+key);dictionaries[languages[i]][key]=values[i].replaceAll('\\n','\n');}}
const aliases={navHelp:'how',edition:'navShop',explore:'navShop',collectionSub:'intro',details:'details',spec:'description',myOrders:'orders',sent:'queued',submitSupport:'support',recoverConfirm:'confirm',stepChoose:'navShop',stepRegister:'register',stepDownload:'download',originalCollection:'navShop',subtitle:'brand',coverAlt:'preview',successPayment:'success',footerHelp:'how',newPassword:'password',emailVerifyTitle:'verify',resetTitle:'reset',resetSuccess:'saved',fileInvalid:'genericError',conflictError:'genericError',authError:'loginRequired',rateLimited:'rateLimited',namedFiles:'uploadInfo',deleteConfirm:'archiveNote',quote:'summary',orderNumber:'orders',emailLanguage:'language',searchOrders:'search',translationMissing:'translationMissing'};
for(const dictionary of Object.values(dictionaries)){for(const [key,target]of Object.entries(aliases))dictionary[key]=dictionary[target];dictionary.steps=[dictionary.login,dictionary.navShop,dictionary.download];dictionary.stepsDesc=[dictionary.loginFirst,dictionary.intro,dictionary.editable];}
const output='// Generated by scripts/build-locales.mjs. Edit scripts/locale-source.mjs.\nexport const dictionaries='+JSON.stringify(dictionaries,null,2)+' as const;\n';
await fs.writeFile('frontend/src/locales/dictionaries.ts',output);await fs.writeFile('backend/src/commerce/dictionaries.ts',output);
await fs.copyFile('backend/src/commerce/constants.ts','frontend/src/locales/constants.ts');
const demoProducts=Object.fromEntries(Object.entries(titles).map(([slug,row])=>[slug,Object.fromEntries(languages.map((lang,i)=>[lang,{title:row.split('|')[i],description:description.split('|')[i],metadata:{...Object.fromEntries(Object.entries(metadata).map(([k,v])=>[k,v.split('|')[i]])),license:dictionaries[lang].licensePolicy}}]))]));
const demoCategories=Object.fromEntries(Object.entries(categories).map(([id,row])=>[id,Object.fromEntries(languages.map((lang,i)=>[lang,row.split('|')[i]]))]));
await fs.writeFile('backend/src/commerce/demo.ts','// Authored translations, generated by build-locales.mjs\nexport const demoProducts='+JSON.stringify(demoProducts,null,2)+' as const;\nexport const demoCategories='+JSON.stringify(demoCategories,null,2)+' as const;\n');
console.log(JSON.stringify({languages:languages.length,keys:Object.keys(dictionaries.en).length,missing:0,englishFallback:false}));
