export const titles={
 'sage-strategy':'青岚 · 战略提案|青嵐 · 策略提案|Sage Strategy|セージ・戦略提案|세이지 전략 제안|Stratégie Sauge|Salbei-Strategie|Estrategia Salvia|Estratégia Sálvia|Стратегия «Шалфей»|استراتيجية المريمية|सेज रणनीति|Strategia Salvia',
 'coral-story':'珊瑚 · 品牌叙事|珊瑚 · 品牌故事|Coral Brand Story|コーラル・ブランドストーリー|코랄 브랜드 이야기|Histoire de marque Corail|Korallen-Markengeschichte|Historia de marca Coral|História da marca Coral|История бренда «Коралл»|قصة علامة المرجان|कोरल ब्रांड की कहानी|Storia del marchio Corallo',
 'midnight-report':'深蓝 · 数据报告|深藍 · 數據報告|Midnight Report|ミッドナイト・データレポート|미드나잇 데이터 보고서|Rapport Minuit|Mitternachtsbericht|Informe Medianoche|Relatório Meia-noite|Отчёт «Полночь»|تقرير منتصف الليل|मिडनाइट रिपोर्ट|Rapporto Mezzanotte',
};
export const categories={business:'商业提案|商業提案|Business|ビジネス提案|비즈니스 제안|Affaires|Geschäftliches|Negocios|Negócios|Бизнес|الأعمال|व्यवसाय|Affari',creative:'品牌创意|品牌創意|Creative|ブランド・クリエイティブ|브랜드 디자인|Création|Kreatives|Creatividad|Criatividade|Творчество|الإبداع|रचनात्मक|Creatività',report:'数据报告|數據報告|Reports|データレポート|데이터 보고서|Rapports|Berichte|Informes|Relatórios|Отчёты|التقارير|रिपोर्ट|Rapporti'};
export const description="用清晰层级和克制配色呈现想法。包含封面、方向、要点、可编辑图表与行动计划。|以清晰層級與精簡配色表達想法。含封面、方向、重點、可編輯圖表與行動計畫。|Present ideas with a considered palette and clear hierarchy. Includes a cover, direction, priorities, an editable chart and next steps.|落ち着いた配色と明確な構成でアイデアを伝えます。表紙、方針、重点、編集可能なグラフ、行動計画を収録。|차분한 색상과 명확한 구성으로 아이디어를 전달하세요. 표지, 방향, 우선순위, 편집 가능한 차트와 실행 계획이 포함됩니다.|Présentez vos idées avec une palette sobre et une hiérarchie claire. Couverture, orientation, priorités, graphique modifiable et prochaines étapes inclus.|Präsentieren Sie Ideen mit ruhigen Farben und klarer Struktur. Enthält Titelblatt, Ausrichtung, Schwerpunkte, bearbeitbares Diagramm und nächste Schritte.|Presenta ideas con una paleta sobria y una jerarquía clara. Incluye portada, dirección, prioridades, un gráfico editable y próximos pasos.|Apresente ideias com cores discretas e organização clara. Inclui capa, direção, prioridades, gráfico editável e próximos passos.|Передавайте идеи с помощью сдержанных цветов и ясной структуры. Обложка, направление, приоритеты, редактируемая диаграмма и план действий.|اعرض أفكارك بألوان هادئة وتنظيم واضح. يتضمن غلافًا واتجاهًا وأولويات ورسمًا بيانيًا قابلًا للتحرير وخطوات تالية.|संतुलित रंगों और स्पष्ट संरचना से विचार प्रस्तुत करें। कवर, दिशा, प्राथमिकताएँ, संपादन योग्य चार्ट और आगे की योजना शामिल हैं।|Presenta le idee con colori sobri e una struttura chiara. Include copertina, direzione, priorità, grafico modificabile e prossimi passi.";
export const metadata={
 editable:'文字、形状、原生图表|文字、形狀、原生圖表|Text, shapes and native charts|テキスト、図形、ネイティブグラフ|텍스트, 도형, 기본 차트|Texte, formes et graphiques natifs|Text, Formen und native Diagramme|Texto, formas y gráficos nativos|Texto, formas e gráficos nativos|Текст, фигуры и встроенные диаграммы|النصوص والأشكال والرسوم البيانية الأصلية|पाठ, आकृतियाँ और मूल चार्ट|Testo, forme e grafici nativi',
 fonts:'Arial 系统字体；不含字体文件|Arial 系統字型；不含字型檔|Arial system font; font files not included|Arial システムフォント、フォントファイルなし|Arial 시스템 글꼴, 글꼴 파일 미포함|Police système Arial ; fichiers non inclus|Systemschrift Arial; Schriftdateien nicht enthalten|Fuente del sistema Arial; archivos no incluidos|Fonte do sistema Arial; arquivos não incluídos|Системный шрифт Arial; файлы шрифтов не входят|خط النظام Arial؛ ملفات الخط غير مضمنة|Arial सिस्टम फ़ॉन्ट; फ़ॉन्ट फ़ाइलें शामिल नहीं|Font di sistema Arial; file del font esclusi',
 images:'自有几何元素；无第三方图片|自有幾何元素；無第三方圖片|Original geometry; no third-party images|独自の幾何図形、外部画像なし|자체 제작 도형, 외부 이미지 없음|Géométrie originale ; aucune image tierce|Eigene Geometrie; keine fremden Bilder|Geometría original; sin imágenes de terceros|Geometria original; sem imagens de terceiros|Авторские геометрические элементы; без сторонних изображений|أشكال هندسية أصلية؛ دون صور خارجية|मूल ज्यामितीय आकृतियाँ; बाहरी चित्र नहीं|Geometria originale; nessuna immagine di terzi',
};
