import fs from 'node:fs/promises';import path from 'node:path';import {randomBytes,randomUUID} from 'node:crypto';import {createRequire} from 'node:module';import {root,pnpm,taskEnv} from './common.mjs';import {startPostgres} from './postgres.mjs';
import {cleanupFixture} from './cleanup.mjs';
const require=createRequire(import.meta.url);const {createUtf8Database}=await import('./postgres.mjs');
export async function fixture(label,port=55433){if(!['browser','integration'].includes(label)||![55433,55434].includes(port))throw new Error('Invalid isolated fixture');const password=randomBytes(32).toString('hex');const name=`workshop_test_${label}_${randomUUID().replaceAll('-','').slice(0,8)}`;const folder=`postgres-${name}`;const pg=await startPostgres(folder,port,password);let db;const artifacts=[];const stop=async()=>{await db?.$disconnect();await pg.stop();await cleanupFixture(name,artifacts);};
  try{await createUtf8Database(pg,name);const c={APP_ENV:'local',PAYMENT_MODE:'mock',PORT:'4100',DATABASE_URL:`postgresql://workshop:${password}@127.0.0.1:${port}/${name}`,PUBLIC_ORIGIN:'http://localhost:3000',SESSION_SECRET:randomBytes(32).toString('hex'),MOCK_SIGNING_KEY:randomBytes(32).toString('hex'),ADMIN_ENCRYPTION_KEY:randomBytes(32).toString('hex'),TEST_ACCESS_PASSWORD:randomBytes(24).toString('hex'),STORAGE_ROOT:path.join(root,'.runtime',name,'storage'),MAIL_TRANSPORT:'outbox',MAIL_FROM:'test@example.test',FX_AUTOMATIC_REFRESH:'false',STORE_ACCESS_MODE:label==='browser'?'account':'password'};
    await fs.mkdir(c.STORAGE_ROOT,{recursive:true});await pnpm(['--filter','backend','migrate'],{env:{...taskEnv,...c}});const {database}=require('../backend/dist/db.js');const {parseConfig}=require('../backend/dist/config.js');const {seed}=require('../backend/dist/seed.js');const {initializeAdmin}=require('../backend/dist/admin-init.js');const config=parseConfig(c);db=database(config.DATABASE_URL);
    // Deterministic test data; never used to claim current market exchange rates.
    const {CURRENCIES}=require('../backend/dist/commerce/constants');await db.fxSnapshot.create({data:{source:'TEST_FIXTURE',base:'CNY',rates:Object.fromEntries(CURRENCIES.map(currency=>[currency,{rate:currency==='CNY'?'1':currency==='JPY'?'23.575':currency==='KRW'?'200.99':currency==='USD'?'0.14925':'0.2',date:new Date().toISOString().slice(0,10)}]))}});await seed(db,config);await require('../backend/dist/commerce/upgrade').upgradeCommerce(db,config);c.PURCHASE_ROOT=config.PURCHASE_ROOT;
    const adminPassword=randomBytes(24).toString('hex');const supportPassword=randomBytes(24).toString('hex');const admin=await initializeAdmin(db,config,{email:'admin@example.test',password:adminPassword,role:'ADMIN'});const support=await initializeAdmin(db,config,{email:'support@example.test',password:supportPassword,role:'SUPPORT'});return {pg,db,config,env:c,name,artifacts,admin:{...admin,password:adminPassword},support:{...support,password:supportPassword},stop};
  }catch(e){await stop();throw e;}
}
