import { fixture } from './fixture.mjs';import {createRequire} from 'node:module';import fs from 'node:fs/promises';import path from 'node:path';import {root} from './common.mjs';
const require=createRequire(import.meta.url);const {createApp}=require('../backend/dist/app');const {run}=require('../backend/test/integration.cjs');
const results=[];let f,server;
try{f=await fixture('integration');server=await createApp(f.config);await server.app.listen(0,'127.0.0.1');const base=await server.app.getUrl();const record=async(id,scenario,action)=>{const start=Date.now();try{await f.db.rateLimit.deleteMany();await action();results.push({id,scenario,status:'PASS',durationMs:Date.now()-start});console.log(`PASS ${id} ${scenario}`);}catch(e){let message=e.message;for(const v of [...Object.values(f.env),f.admin.password,f.admin.secret,f.support.password,f.support.secret])if(typeof v==='string'&&v.length>15)message=message.replaceAll(v,'[REDACTED]');results.push({id,scenario,status:'FAIL',error:message,durationMs:Date.now()-start});console.error(`FAIL ${id}: ${message}`);console.error(String(e.stack).split("\n").filter(line=>line.trim().startsWith("at ")).slice(0,6).join("\n"));}};
  const outcome=await run({...f,...server,base},record);
  await record('MAIL-SMTP','真实 SMTP 协议发送到仅本机测试收件服务',()=>require('../backend/test/smtp.cjs').check(server.shop));
  await record('DEV-AUTH','免登录买家与后台、购买下载聊天、二次验证豁免、会话隔离及关闭恢复鉴权',()=>require('../backend/test/dev-auth.cjs').check({...f,...server,base}));
  await fs.writeFile(path.join(root,'docs/evidence/openapi.json'),JSON.stringify(server.document,null,2));
  const {recoveryCheck}=await import('./recovery-check.mjs');await recoveryCheck(f,server,outcome,record);
  await record('T30/T31','正式环境启动拒绝模拟支付、无渠道结账关闭、无模拟路由',async()=>{const assert=await import('node:assert/strict');const {parseConfig}=require('../backend/dist/config');assert.throws(()=>parseConfig({...f.env,APP_ENV:'production'}));const config=parseConfig({...f.env,APP_ENV:'production',PAYMENT_MODE:'live',PUBLIC_ORIGIN:'https://store.example.test',MAIL_TRANSPORT:'smtp',SMTP_HOST:'127.0.0.1',SMTP_PORT:'1025'});const production=await createApp(config);try{await production.app.listen(0,'127.0.0.1');const url=await production.app.getUrl();const {BrowserSession}=require('../backend/test/integration.cjs');const b=await new BrowserSession(url,config).init(false);assert.equal((await b.call('/mock/orders/00000000-0000-4100-8000-000000000000/scenario','POST',{scenario:'success'})).status,404);assert.equal((await fetch(url+'/api/v1/payments/webhooks/mock',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).status,404);assert.equal((await b.call('/session')).data.checkoutEnabled,false);}finally{await production.app.close();await production.db.$disconnect();}});
}catch(e){console.error('Integration setup failed:',e.name,e.message?.replace(/postgresql:\/\/\S+/g,'[REDACTED]'));process.exitCode=1;}finally{await server?.app.close();await server?.db.$disconnect();await f?.stop();await fs.mkdir(path.join(root,'docs/evidence'),{recursive:true});await fs.writeFile(path.join(root,'docs/evidence/integration.json'),JSON.stringify({date:'2026-10-06',database:'PostgreSQL 18.4 native, isolated project cluster',results},null,2));if(results.some(r=>r.status==='FAIL')||!results.length)process.exitCode=1;console.log(`Integration: ${results.filter(r=>r.status==='PASS').length} passed, ${results.filter(r=>r.status==='FAIL').length} failed`);process.exit(process.exitCode||0);}
