export const operationsRows=String.raw`
uploadAction|上传|上傳|Upload|アップロード|업로드|Téléversement|Upload|Subida|Envio|Загрузка|الرفع|अपलोड|Caricamento
operationSuccess|成功|成功|Succeeded|完了|완료|Réussi|Erfolgreich|Correcto|Concluído|Успешно|تم بنجاح|सफल|Completato
operationFailed|失败|失敗|Failed|失敗|실패|Échec|Fehlgeschlagen|Falló|Falhou|Ошибка|فشل|विफल|Non riuscito
previewRendering|上传完成，正在生成 PPT 预览图…|上傳完成，正在產生 PPT 預覽圖…|Uploaded. Generating slide previews…|アップロード完了。プレビューを生成中…|업로드 완료. 슬라이드 미리보기 생성 중…|Envoi terminé. Création des aperçus…|Upload abgeschlossen. Vorschauen werden erstellt…|Subida completa. Generando vistas previas…|Envio concluído. Gerando prévias…|Загрузка завершена. Создание превью…|اكتمل الرفع. جارٍ إنشاء المعاينات…|अपलोड पूरा। पूर्वावलोकन बन रहे हैं…|Caricamento completato. Creazione anteprime…
previewGenerated|已生成 {count} 张预览图|已產生 {count} 張預覽圖|{count} previews generated|プレビューを {count} 枚生成しました|미리보기 {count}개 생성됨|{count} aperçus créés|{count} Vorschauen erstellt|{count} vistas previas generadas|{count} prévias geradas|Создано превью: {count}|تم إنشاء {count} معاينات|{count} पूर्वावलोकन बनाए गए|{count} anteprime generate
previewRenderFailed|预览生成失败，原文件未替换，请检查文件后重试|預覽產生失敗，原檔未替換，請檢查檔案後重試|Preview generation failed; original unchanged. Check the file and retry|プレビュー生成失敗。元ファイルは変更されていません。確認して再試行してください|미리보기 생성 실패. 원본은 유지됩니다. 파일 확인 후 재시도하세요|Échec des aperçus. Original conservé. Vérifiez le fichier et réessayez|Vorschau fehlgeschlagen. Original unverändert. Datei prüfen und erneut versuchen|Error de vista previa. Original conservado. Revisa el archivo y reintenta|Falha na prévia. Original preservado. Verifique o arquivo e tente novamente|Не удалось создать превью. Оригинал сохранён. Проверьте файл и повторите|فشل إنشاء المعاينة. الأصل محفوظ. تحقق من الملف وأعد المحاولة|पूर्वावलोकन विफल। मूल फ़ाइल सुरक्षित है। फ़ाइल जाँचकर फिर कोशिश करें|Anteprima non riuscita. Originale conservato. Controlla il file e riprova
previewBusy|预览服务繁忙，请稍后重试|預覽服務忙碌，請稍後重試|Preview service busy; retry shortly|プレビュー処理中です。後で再試行してください|미리보기 서비스가 바쁩니다. 잠시 후 재시도하세요|Service d’aperçu occupé. Réessayez bientôt|Vorschaudienst ausgelastet. Später erneut versuchen|Servicio de vista previa ocupado. Reintenta después|Serviço de prévia ocupado. Tente novamente em breve|Сервис превью занят. Повторите позже|خدمة المعاينة مشغولة. حاول لاحقًا|पूर्वावलोकन सेवा व्यस्त है। थोड़ी देर बाद कोशिश करें|Servizio anteprime occupato. Riprova tra poco
downloadIncomplete|文件未完整下载，请重试|檔案未完整下載，請重試|Download incomplete; retry|ダウンロードが未完了です。再試行してください|다운로드 미완료. 재시도하세요|Téléchargement incomplet. Réessayez|Download unvollständig. Erneut versuchen|Descarga incompleta. Reintenta|Download incompleto. Tente novamente|Загрузка неполная. Повторите|التنزيل غير مكتمل. أعد المحاولة|डाउनलोड अधूरा है। फिर कोशिश करें|Download incompleto. Riprova
invalidPptx|请选择有效的 PPTX 文件，不能包含宏或外部引用|請選擇有效的 PPTX 檔案，不可包含巨集或外部參照|Select a valid PPTX without macros or external references|マクロや外部参照のない有効な PPTX を選択してください|매크로나 외부 참조가 없는 유효한 PPTX를 선택하세요|Choisissez un PPTX valide sans macros ni références externes|Gültige PPTX ohne Makros oder externe Verweise auswählen|Selecciona un PPTX válido sin macros ni referencias externas|Selecione um PPTX válido sem macros ou referências externas|Выберите корректный PPTX без макросов и внешних ссылок|اختر PPTX صالحًا دون وحدات ماكرو أو مراجع خارجية|मैक्रो या बाहरी संदर्भ के बिना मान्य PPTX चुनें|Scegli un PPTX valido senza macro o riferimenti esterni
sendMessage|发送消息|傳送訊息|Send message|メッセージを送信|메시지 보내기|Envoyer le message|Nachricht senden|Enviar mensaje|Enviar mensagem|Отправить сообщение|إرسال رسالة|संदेश भेजें|Invia messaggio
chat|消息沟通|訊息溝通|Messages|メッセージ|메시지|Messages|Nachrichten|Mensajes|Mensagens|Сообщения|الرسائل|संदेश|Messaggi
contactSeller|在线客服|線上客服|Live support|オンラインサポート|실시간 상담|Assistance en ligne|Live-Support|Atención en línea|Atendimento online|Онлайн-поддержка|الدعم المباشر|ऑनलाइन सहायता|Assistenza in linea
storeEntry|前往商城|前往商城|Open storefront|ストアを開く|스토어 열기|Ouvrir la boutique|Shop öffnen|Abrir tienda|Abrir loja|Открыть магазин|افتح المتجر|स्टोर खोलें|Apri negozio
unresolved|待解决|待解決|Unresolved|未解決|미해결|À résoudre|Offen|Pendiente|Pendente|Не решено|غير محلول|अनसुलझा|Da risolvere
resolved|已解决|已解決|Resolved|解決済み|해결됨|Résolu|Gelöst|Resuelto|Resolvido|Решено|تم الحل|हल किया गया|Risolto
ignored|忽略|忽略|Ignored|対応不要|무시됨|Ignoré|Ignoriert|Ignorado|Ignorado|Пропущено|متجاهل|अनदेखा|Ignorato
newMemo|新增备忘问题|新增備忘問題|Add a memo|メモを追加|메모 추가|Ajouter une note|Notiz hinzufügen|Añadir nota|Adicionar nota|Добавить заметку|أضف ملاحظة|नोट जोड़ें|Aggiungi nota
memoTitle|备忘标题|備忘標題|Memo title|メモのタイトル|메모 제목|Titre de la note|Notiztitel|Título de la nota|Título da nota|Заголовок заметки|عنوان الملاحظة|नोट का शीर्षक|Titolo della nota
memo|个人备忘|個人備忘|Private memo|個人メモ|개인 메모|Note privée|Private Notiz|Nota privada|Nota privada|Личная заметка|ملاحظة خاصة|निजी नोट|Nota privata
chatPlaceholder|输入消息，与商家沟通…|輸入訊息，與商家溝通…|Write a message…|メッセージを入力…|메시지를 입력하세요…|Écrivez un message…|Nachricht schreiben…|Escribe un mensaje…|Escreva uma mensagem…|Введите сообщение…|اكتب رسالة…|संदेश लिखें…|Scrivi un messaggio…
noMessages|还没有消息，欢迎发起沟通|尚無訊息，歡迎開始溝通|No messages yet. Start a conversation.|メッセージはまだありません|아직 메시지가 없습니다|Aucun message. Lancez la conversation.|Noch keine Nachrichten|Aún no hay mensajes|Ainda não há mensagens|Сообщений пока нет|لا رسائل بعد|अभी कोई संदेश नहीं|Ancora nessun messaggio
attachFile|添加附件|新增附件|Attach a file|ファイルを添付|파일 첨부|Joindre un fichier|Datei anhängen|Adjuntar archivo|Anexar arquivo|Прикрепить файл|إرفاق ملف|फ़ाइल संलग्न करें|Allega file
removeAttachment|移除附件|移除附件|Remove attachment|添付を削除|첨부 삭제|Retirer la pièce jointe|Anhang entfernen|Quitar archivo adjunto|Remover anexo|Удалить вложение|إزالة المرفق|अनुलग्नक हटाएँ|Rimuovi allegato
downloadFile|点击下载|點擊下載|Download|ダウンロード|다운로드|Télécharger|Herunterladen|Descargar|Baixar|Скачать|تنزيل|डाउनलोड|Scarica
fileTooLarge|文件太大：聊天附件和图片最多 1024 MB，商品 PPTX 最多 1024 MB|檔案太大：附件及圖片上限 1024 MB，商品 PPTX 上限 1024 MB|File too large: chat and images 1024 MB, product PPTX 1024 MB|上限は添付と画像1024 MB、商品PPTX 1024 MBです|첨부 및 이미지 1024 MB, 상품 PPTX 1024 MB 제한|Limite : fichiers et images 1024 Mo, PPTX 1024 Mo|Limit: Anhänge und Bilder 1024 MB, PPTX 1024 MB|Límite: archivos e imágenes 1024 MB, PPTX 1024 MB|Limite: anexos e imagens 1024 MB, PPTX 1024 MB|Лимит: вложения и изображения 1024 МБ, PPTX 1024 МБ|الحد: المرفقات والصور 1024 ميغابايت، PPTX ‏1024 ميغابايت|सीमा: संलग्नक और चित्र 1024 MB, PPTX 1024 MB|Limite: allegati e immagini 1024 MB, PPTX 1024 MB
chatDragHelp|拖动调整位置；方向键移动，Home 恢复默认位置|拖動調整位置；方向鍵移動，Home 恢復預設位置|Drag to reposition; arrow keys move, Home resets|ドラッグで移動、矢印キーで調整、Homeで初期位置に戻す|드래그 또는 방향키로 이동, Home으로 초기화|Glisser pour déplacer ; flèches pour ajuster, Home pour réinitialiser|Ziehen oder Pfeiltasten zum Verschieben, Home zum Zurücksetzen|Arrastra o usa las flechas; Home restablece|Arraste ou use as setas; Home restaura|Перетащите или используйте стрелки; Home сбрасывает|اسحب أو استخدم الأسهم للنقل، Home لإعادة الموضع|खींचें या तीर कुंजियों से हिलाएँ; Home से रीसेट करें|Trascina o usa le frecce; Home ripristina
attachTooLarge|文件超过 1024 MB，请压缩后再发送|檔案超過 1024 MB，請壓縮後再傳送|File exceeds 1024 MB — please compress it first|ファイルが 1024 MB を超えています。圧縮してから送信してください|파일이 1024 MB를 초과합니다. 압축 후 전송해 주세요|Le fichier dépasse 1024 Mo, veuillez le compresser|Datei überschreitet 1024 MB, bitte zuerst komprimieren|El archivo supera 1024 MB, comprímelo antes|O arquivo excede 1024 MB, comprima antes|Файл превышает 1024 МБ, сожмите его|الملف يتجاوز 1024 ميغابايت، يرجى ضغطه أولاً|फ़ाइल 1024 MB से बड़ी है, कृपया पहले संपीड़ित करें|Il file supera 1024 MB, comprimilo prima
selectConversation|选择左侧对话查看并回复|選擇左側對話查看並回覆|Select a conversation to reply|会話を選んで返信|대화를 선택하여 답장하세요|Sélectionnez une conversation|Unterhaltung auswählen|Selecciona una conversación|Selecione uma conversa|Выберите переписку|اختر محادثة للرد|जवाब देने के लिए बातचीत चुनें|Seleziona una conversazione
chatConnecting|连接中，消息已保存|連線中，訊息已保存|Connecting; messages are saved|接続中・履歴は保存済み|연결 중, 메시지는 저장됨|Connexion, messages enregistrés|Verbindung wird hergestellt|Conectando; mensajes guardados|Conectando; mensagens salvas|Подключение, сообщения сохранены|جارٍ الاتصال، الرسائل محفوظة|जुड़ रहा है; संदेश सुरक्षित हैं|Connessione; messaggi salvati
chatConnected|实时连接已建立|即時連線已建立|Connected|接続済み|연결됨|Connecté|Verbunden|Conectado|Conectado|Подключено|متصل|जुड़ा हुआ|Connesso
buyerRole|买家|買家|Buyer|購入者|구매자|Acheteur|Käufer|Comprador|Comprador|Покупатель|المشتري|खरीदार|Acquirente
sellerRole|商家|商家|Seller|販売者|판매자|Vendeur|Verkäufer|Vendedor|Vendedor|Продавец|البائع|विक्रेता|Venditore
priceAsc|价格从低到高|價格由低到高|Price: low to high|価格の安い順|가격 낮은 순|Prix croissant|Preis aufsteigend|Precio ascendente|Preço crescente|Цена по возрастанию|السعر من الأقل للأعلى|कीमत कम से अधिक|Prezzo crescente
priceDesc|价格从高到低|價格由高到低|Price: high to low|価格の高い順|가격 높은 순|Prix décroissant|Preis absteigend|Precio descendente|Preço decrescente|Цена по убыванию|السعر من الأعلى للأقل|कीमत अधिक से कम|Prezzo decrescente
minPrice|最低价格|最低價格|Minimum price|最低価格|최저 가격|Prix minimum|Mindestpreis|Precio mínimo|Preço mínimo|Минимальная цена|أقل سعر|न्यूनतम कीमत|Prezzo minimo
maxPrice|最高价格|最高價格|Maximum price|最高価格|최고 가격|Prix maximum|Höchstpreis|Precio máximo|Preço máximo|Максимальная цена|أعلى سعر|अधिकतम कीमत|Prezzo massimo
defaultSort|推荐排序|推薦排序|Recommended order|おすすめ順|추천 순|Ordre recommandé|Empfohlene Reihenfolge|Orden recomendado|Ordem recomendada|Рекомендуемый порядок|الترتيب المقترح|अनुशंसित क्रम|Ordine consigliato
applyFilters|应用筛选|套用篩選|Apply filters|絞り込む|필터 적용|Appliquer|Filter anwenden|Aplicar filtros|Aplicar filtros|Применить фильтры|طبّق الفلاتر|फ़िल्टर लागू करें|Applica filtri
resetFilters|清除筛选|清除篩選|Clear filters|条件をクリア|필터 지우기|Effacer les filtres|Filter löschen|Borrar filtros|Limpar filtros|Сбросить фильтры|امسح الفلاتر|फ़िल्टर हटाएँ|Cancella filtri
invalidPriceRange|请输入有效价格区间，最低价不能高于最高价|請輸入有效價格區間，最低價不得高於最高價|Enter a valid price range; minimum must not exceed maximum|最低価格は最高価格以下にしてください|최저 가격은 최고 가격 이하여야 합니다|La valeur minimale doit être inférieure au maximum|Mindestpreis darf Höchstpreis nicht übersteigen|El mínimo no debe superar el máximo|O mínimo não pode exceder o máximo|Минимум не должен превышать максимум|يجب ألا يتجاوز الحد الأدنى الحد الأعلى|न्यूनतम कीमत अधिकतम से अधिक नहीं होनी चाहिए|Il minimo non può superare il massimo
accountNotFound|该邮箱尚未注册，请先注册账号|此信箱尚未註冊，請先註冊帳號|This email is not registered. Create an account.|このメールアドレスは未登録です|등록되지 않은 이메일입니다|Cet e-mail n'est pas inscrit|Diese E-Mail ist nicht registriert|Este correo no está registrado|Este e-mail não está cadastrado|Эта почта не зарегистрирована|هذا البريد غير مسجل|यह ईमेल पंजीकृत नहीं है|Questa e-mail non è registrata
wrongPassword|密码错误，请重新输入或重设密码|密碼錯誤，請重新輸入或重設|Incorrect password. Try again or reset it.|パスワードが違います。再入力または再設定してください|비밀번호가 틀립니다. 다시 입력하거나 재설정하세요|Mot de passe incorrect. Réessayez ou réinitialisez-le.|Passwort falsch. Erneut eingeben oder zurücksetzen.|Contraseña incorrecta. Reintenta o restablécela.|Senha incorreta. Tente novamente ou redefina.|Неверный пароль. Повторите или сбросьте.|كلمة المرور خاطئة، أعد المحاولة أو تعيينها|पासवर्ड गलत है। फिर कोशिश करें या रीसेट करें|Password errata. Riprova o reimpostala.
invalidCode|验证码错误或已过期，请输入验证器当前验证码|驗證碼錯誤或過期，請輸入目前驗證碼|Incorrect or expired code. Enter the current authenticator code.|認証コードが違うか期限切れです|인증 코드가 틀리거나 만료되었습니다|Code incorrect ou expiré|Code falsch oder abgelaufen|Código incorrecto o caducado|Código incorreto ou expirado|Код неверен или истёк|الرمز خاطئ أو منتهي الصلاحية|कोड गलत है या समय समाप्त हो गया|Codice errato o scaduto
rateLimited|尝试过于频繁，请稍后再试|嘗試過於頻繁，請稍後再試|Too many attempts. Try again later.|試行回数が多すぎます。後ほど再試行してください|시도가 너무 많습니다. 나중에 다시 시도하세요|Trop de tentatives. Réessayez plus tard.|Zu viele Versuche. Später erneut versuchen.|Demasiados intentos. Prueba más tarde.|Muitas tentativas. Tente mais tarde.|Слишком много попыток. Повторите позже.|محاولات كثيرة، حاول لاحقًا|बहुत अधिक प्रयास। बाद में कोशिश करें|Troppi tentativi. Riprova più tardi.
accountDisabled|账号已停用，请联系商家|帳號已停用，請聯絡商家|Account disabled. Contact the seller.|アカウントが無効です。販売者に連絡してください|계정이 비활성화되었습니다|Compte désactivé. Contactez le vendeur.|Konto deaktiviert. Verkäufer kontaktieren.|Cuenta desactivada. Contacta al vendedor.|Conta desativada. Contate o vendedor.|Аккаунт отключён. Свяжитесь с продавцом.|الحساب معطل، تواصل مع البائع|खाता बंद है। विक्रेता से संपर्क करें|Account disattivato. Contatta il venditore.
invalidInput|输入格式不正确，请检查必填项和字符长度|輸入格式錯誤，請檢查必填欄位與長度|Check required fields, format and length.|必須項目・形式・文字数を確認してください|필수 항목, 형식과 길이를 확인하세요|Vérifiez les champs, le format et la longueur|Pflichtfelder, Format und Länge prüfen|Revisa campos, formato y longitud|Confira campos, formato e tamanho|Проверьте поля, формат и длину|تحقق من الحقول والتنسيق والطول|फ़ील्ड, प्रारूप और लंबाई जाँचें|Controlla campi, formato e lunghezza
accountExistsNotice|该邮箱已经注册，请登录或重设密码|此信箱已註冊，請登入或重設密碼|This email is already registered. Sign in or reset your password.|登録済みです。ログインまたは再設定してください|이미 등록된 이메일입니다|E-mail déjà inscrit. Connectez-vous ou réinitialisez.|E-Mail bereits registriert. Anmelden oder zurücksetzen.|Correo ya registrado. Inicia sesión o restablece.|E-mail já cadastrado. Entre ou redefina.|Почта зарегистрирована. Войдите или сбросьте пароль.|البريد مسجل، سجّل الدخول أو أعد تعيين كلمة المرور|ईमेल पंजीकृत है। लॉग इन करें या पासवर्ड रीसेट करें|E-mail già registrata. Accedi o reimposta la password.
shopMode|商城运行模式|商城運行模式|Store mode|ストア運用モード|스토어 운영 모드|Mode de la boutique|Shop-Modus|Modo de la tienda|Modo da loja|Режим магазина|وضع المتجر|स्टोर मोड|Modalità negozio
modeTest|测试模式|測試模式|Test mode|テストモード|테스트 모드|Mode test|Testmodus|Modo de prueba|Modo de teste|Тестовый режим|وضع الاختبار|परीक्षण मोड|Modalità di prova
modeNormal|正常使用|正常使用|Normal operation|通常運用|정상 운영|Fonctionnement normal|Normalbetrieb|Uso normal|Uso normal|Обычный режим|التشغيل العادي|सामान्य संचालन|Funzionamento normale
modeHelp|模式只在此处显示；正常模式在真实支付接入前关闭购买|模式僅在此顯示；正常模式接入真實支付前關閉購買|Mode is shown here only. Normal purchases stay closed until live payments are connected.|通常運用の購入には実決済の接続が必要です|실제 결제 연동 전에는 정상 모드 구매가 닫힙니다|Les achats normaux attendent un paiement réel connecté|Normale Käufe erfordern eine echte Zahlungsanbindung|Las compras normales requieren pagos reales conectados|Compras normais exigem pagamentos reais conectados|Обычные покупки требуют подключения реальных платежей|الشراء العادي يتطلب ربط الدفع الحقيقي|सामान्य खरीद के लिए वास्तविक भुगतान जोड़ना आवश्यक है|Gli acquisti normali richiedono pagamenti reali collegati
modeForbidden|此部署环境不允许启用模拟支付|此部署環境禁止模擬付款|This environment forbids simulated payments|この環境では模擬決済は禁止です|이 환경은 모의 결제를 금지합니다|Paiements simulés interdits ici|Simulierte Zahlungen hier verboten|Pagos simulados prohibidos aquí|Pagamentos simulados proibidos aqui|Имитация платежей запрещена|الدفع التجريبي ممنوع هنا|यह वातावरण नकली भुगतान की अनुमति नहीं देता|Pagamenti simulati vietati qui
payNow|确认付款|確認付款|Pay now|支払う|결제하기|Payer|Jetzt bezahlen|Pagar|Pagar agora|Оплатить|ادفع الآن|भुगतान करें|Paga ora
overviewSummary|经营概览|經營概覽|Business overview|運営概要|운영 개요|Vue d'ensemble|Geschäftsübersicht|Resumen del negocio|Visão geral|Обзор магазина|نظرة على النشاط|व्यवसाय अवलोकन|Panoramica attività
todayOrders|今日订单|今日訂單|Orders today|本日の注文|오늘 주문|Commandes du jour|Bestellungen heute|Pedidos de hoy|Pedidos de hoje|Заказы сегодня|طلبات اليوم|आज के ऑर्डर|Ordini di oggi
monthOrders|本月订单|本月訂單|Orders this month|今月の注文|이번 달 주문|Commandes du mois|Bestellungen diesen Monat|Pedidos del mes|Pedidos do mês|Заказы за месяц|طلبات هذا الشهر|इस माह के ऑर्डर|Ordini del mese
publishedProducts|已上架商品|已上架商品|Published products|公開中の商品|판매 중 상품|Produits en ligne|Veröffentlichte Produkte|Productos publicados|Produtos publicados|Опубликованные товары|المنتجات المنشورة|प्रकाशित उत्पाद|Prodotti pubblicati
draftProducts|未上架商品|未上架商品|Draft products|下書きの商品|미판매 상품|Produits en brouillon|Produktentwürfe|Productos en borrador|Rascunhos|Черновики товаров|مسودات المنتجات|प्रारूप उत्पाद|Prodotti in bozza
totalCustomers|买家总数|買家總數|Total customers|購入者総数|총 구매자|Clients au total|Kunden insgesamt|Clientes totales|Total de clientes|Всего покупателей|إجمالي المشترين|कुल ग्राहक|Clienti totali
ordersCount|累计订单|累計訂單|Total orders|注文総数|전체 주문|Commandes totales|Bestellungen insgesamt|Pedidos totales|Total de pedidos|Всего заказов|إجمالي الطلبات|कुल ऑर्डर|Ordini totali
pendingRefunds|待审核退款|待審核退款|Refunds awaiting review|審査待ち返金|검토 대기 환불|Remboursements à examiner|Offene Erstattungsprüfungen|Reembolsos por revisar|Reembolsos em análise|Возвраты на проверке|استردادات قيد المراجعة|समीक्षा हेतु धनवापसी|Rimborsi da verificare
openTickets|待解决问题|待解決問題|Open issues|未解決の問題|미해결 문제|Problèmes ouverts|Offene Anliegen|Problemas pendientes|Problemas pendentes|Открытые вопросы|مشكلات مفتوحة|अनसुलझे मुद्दे|Problemi aperti
activeEntitlements|有效下载权限|有效下載權限|Active downloads|有効なダウンロード権限|유효 다운로드 권한|Accès actifs|Aktive Downloadrechte|Descargas activas|Downloads ativos|Активные права скачивания|صلاحيات تنزيل نشطة|सक्रिय डाउनलोड अधिकार|Accessi download attivi
unreadConversations|待回复对话|待回覆對話|Conversations awaiting reply|返信待ちの会話|답장 대기 대화|Conversations à répondre|Unbeantwortete Unterhaltungen|Conversaciones por responder|Conversas sem resposta|Переписки без ответа|محادثات بانتظار الرد|उत्तर की प्रतीक्षा में बातचीत|Conversazioni da rispondere
paymentCompletion|付款完成率|付款完成率|Payment completion rate|支払完了率|결제 완료율|Taux de paiement|Zahlungsabschlussrate|Tasa de pago|Taxa de conclusão de pagamento|Доля оплаченных заказов|نسبة إتمام الدفع|भुगतान पूर्णता दर|Tasso di completamento pagamento
recentOrders|最近订单|最近訂單|Recent orders|最近の注文|최근 주문|Commandes récentes|Letzte Bestellungen|Pedidos recientes|Pedidos recentes|Последние заказы|أحدث الطلبات|हाल के ऑर्डर|Ordini recenti
weekActivity|近七日订单走势|近七日訂單趨勢|Orders over seven days|直近7日間の注文|최근 7일 주문|Commandes sur sept jours|Bestellungen der letzten sieben Tage|Pedidos de siete días|Pedidos de sete dias|Заказы за семь дней|طلبات آخر سبعة أيام|पिछले सात दिन के ऑर्डर|Ordini degli ultimi sette giorni
`.trim();
